  services:
    jenkins-api:
      image: enoqueneres94/jenkins-api:v1
      ports:
        - "8084:8084"
      networks:
        - rede-local

  networks:
    rede-local:
      driver: bridge
      name: rede-local