pipeline {
    agent any
    tools {
            maven 'Maven 3.6.3' // This should match the name in Global Tool Configuration
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'GIT', url: 'https://github.com/thiago-jv/SPRINGBOOT_JENKINS.git'
            }
        }
        stage('Build') {
            steps {
                dir('jenkins') {
                      sh 'mvn clean package'
                }
            }
        }
        stage('Deploy') {
            steps {
            dir('jenkins') {
                    sh 'docker compose up -d'
                }
            }
        }

    }
}