pipeline {
    agent any
    environment {
            MVN_HOME = '/usr/share/maven'
        }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'GIT', url: 'https://github.com/thiago-jv/SPRINGBOOT_JENKINS.git'
            }
        }
        stage('Build') {
            steps {
                dir('jenkins') {
                  withMaven(maven: 'Maven 3.6.3') {
                      sh 'mvn clean package'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
            dir('jenkins') {
                    sh 'docker compose up -d'
                }
            }
        }

    }
}